### ISSUE TITLE
pydantic todo list - validators

### ISSUE THREAD

**Issue by dayantur** [UMEP-dev/SUEWS#300]
Todo list:

- [x]  @model_validator (validate_porosity_range) in class DectrProperties
- [x] @model_validator (validate_cap_range) in class DectrProperties
- [x] @model_validator (validate_albedo_range) in class VegetatedSurfaceProperties
- [x] @model_validator (validate_albedo_range) in class VegetatedSurfaceProperties
- [x] @model_validator (validate_crw_range and validate_snowalb_range) in SnowParams
- [x] ge=0.1 and le=0.9 for pormin_dec and pormax_dec
- [x] @model_validator (validate_rsl_zd_range) in class BuildingProperties
- [x] @model_validator (validate_storageheatmethod) in class SUEWSConfig

**Comment by dayantur** [comment]
Hi @sunt05 -- I added a new @model_validator (storageheatmethod_validator) in class SUEWSConfig.
To make it work, I added some code lines at the beginning of def_config_suews.py related to loading ohm coefficients ranges from an Excel file. I also added the excel file (SUEWS_OHMCoefficients) and a yaml file (config-suews-ohmcoefftest) generated by @MatthewPaskin and populated with some valid ohm coefficients to run the checks.

You can just check my commits at dayantur/adding_pydantic_rules - and go ahead with the merge if you don't find any major conflicts/issues.
